routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// homepage
Route::get('/', 'HomeController@index')->name('home');

// projects
Route::get('projets', 'ProjectsController@index')->name('front.projects.index');
Route::get('projets/{project}', 'ProjectsController@show')->name('front.projects.show');

// blog
Route::get('blog', 'PostsController@index')->name('front.blog.index');
Route::get('blog/{post}', 'PostsController@show')->name('front.blog.show');

Route::get('mentions-legales', 'MentionsController@index')->name('mentions');



// Authentification
Route::get('/register', 'Auth\RegisterController@create')->name('register.create');
Route::get('/login', 'Auth\LoginController@create')->name('login');
Route::get('/logout', 'Auth\LoginController@destroy')->name('logout');
Route::get('/password-request', 'Auth\LoginController@lostPassword')->name('password.request');

Route::post('/register', 'Auth\RegisterController@store')->name('register.store');
Route::post('/login', 'Auth\LoginController@store')->name('login.store');

// zone admin
Route::group(['prefix' => 'admin',  'middleware' => ['role:admin']], function()
{
    Route::get('/', 'Admin\DashboardController@index')->name('dashboard.index');

    Route::any('user-data', 'Admin\UsersController@ajaxListing')->name('datatables.data');
    Route::any('project-data', 'Admin\ProjectsController@ajaxListing')->name('datatables.projectData');
    Route::any('blog-data', 'Admin\PostsController@ajaxListing')->name('datatables.blogData');

    // route page d'accueil
    Route::resource('homepage', 'Admin\HomeController');

    // users, profile
    Route::get('users/{user}/delete', 'Admin\UsersController@destroy')->name('users.destroy');
    Route::resource('users', 'Admin\UsersController', ['except' => 'destroy']);

    // projects
    Route::get('projects/{project}/delete', 'Admin\ProjectsController@destroy')->name('projects.destroy');
    Route::resource('projects', 'Admin\ProjectsController', ['except' => 'destroy']);

    // blog
    Route::get('blog/{blog}/delete', 'Admin\PostsController@destroy')->name('blog.destroy');
    Route::resource('blog', 'Admin\PostsController', ['except' => 'destroy']);


});

resources/views/admin/blog/_form.blade.php
<div class="form-group form-custom <?php if($errors->has('title')) { echo 'has-danger';} ?>">
    <div class="col-3">
        {!! Form::label('title', 'Titre de l\'article', ['class' => 'control-label']) !!}
    </div>

    <div class="col-12">
        {!! Form::text('title', null, ['class' => 'form-control']) !!}
        {!! $errors->first('title', '<span class="help-block">Ce champ est obligatoire</span>') !!}
    </div>
</div>

<div class="form-group form-custom <?php if($errors->has('body')) { echo 'has-danger';} ?>">
    <div class="col-3">
        {!! Form::label('body', 'Contenu de l\'article', ['class' => 'control-label']) !!}
    </div>

    <div class="col-12">

        {!! Form::textarea('body', null, ['class' => 'form-control', 'id' => 'ckeditor']) !!}
        {!! $errors->first('body', '<span class="help-block">Ce champ est obligatoire</span>') !!}
    </div>
</div>

@push('scripts')
<script>
    CKEDITOR.replace( 'ckeditor' );
</script>
@endpush
<div class="form-group form-custom <?php if($errors->has('illustration')) { echo 'has-danger';} ?>">
    <div class="col-3">
        {!! Form::label('illustration', 'Illustration de l\'article', ['class' => 'control-label']) !!}
    </div>

    <div class="col-12">
        {!! Form::file('illustration', null, ['class' => 'form-control']) !!}
        {!! $errors->first('illustration', '<span class="help-block">Ce champ est obligatoire</span>') !!}
    </div>
</div>

resources/views/admin/blog/create.blade.php
@extends('admin.layouts.app')

@section('title')
    Créer un nouvel article - @parent
@endsection

@section('content')
    @include('layouts.errors._errors')

    <div class="form-container">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{ route('dashboard.index') }}">Tableau de bord</a></li>
            <li class="breadcrumb-item"><a href="{{ route('blog.index') }}">Index Blog</a></li>
            <li class="breadcrumb-item">Création d'un nouvel article</li>
        </ol>

        <h1 title="Création d'un nouveau Article">Création d'un nouveau Article</h1>
        {!! Form::open(['route' => ['blog.store'], 'method' => 'post',
                    'enctype' => 'multipart/form-data', 'class' => ' form-bordered form-horizontal']) !!}

        @include('admin.blog._form')

        <button class="btn" href="{{ route('blog.index') }}">Retour</button>
        <button type="submit" class="btn blue-button">Créer un nouvel article</button>
        {!! Form::close() !!}
    </div>
@endsection

resources/views/admin/blog/edit.blade.php
@extends('admin.layouts.app')

@section('title')
    Editer un article - @parent
@endsection

@section('content')

    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{ route('dashboard.index') }}">Tableau de bord</a></li>
        <li class="breadcrumb-item"><a href="{{ route('blog.index') }}">Index Blog</a></li>
        <li class="breadcrumb-item">Editer un article</li>
    </ol>
    <h1>Editer un article</h1>

    {!! Form::model($post, ['route' => ['blog.update', $post->id], 'method' => 'patch',
            'enctype' => 'multipart/form-data', 'class' => ' form-bordered']) !!}

    @include('admin.blog._form')

    <button class="btn" href="{{ route('blog.index') }}">Retour</button>
    <button type="submit" class="btn blue-button">Mettre à jour</button>
    {!! Form::close() !!}

@endsection

resources/views/admin/blog/index.blade.php
@extends('admin.layouts.app')

@section('title')
    Gestion des articles - @parent
@endsection

@section('content')
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{ route('dashboard.index') }}">Tableau de bord</a></li>
        <li class="breadcrumb-item">Index Blog</li>
    </ol>

    <a class="blue-button" href="{{ route('blog.create') }}">Créer un nouvel article</a>
    <h1>Index Blog</h1>


    <table class="table table-bordered table-striped dataTable" id="listingBlog">
        <thead>
        <th>ID</th>
        <th>Titre</th>
        <th>Actions</th>
        </thead>


    </table>

    @push('scripts')
    <script>
        $(document).ready(function () {
            $('#listingBlog').DataTable({
                processing: true,
                serverSide: true,
                ordering: true,
                language: {
                    processing: "Traitement en cours...",
                    search: 'Recherche : ',
                    lengthMenu: "Afficher _MENU_ &eacute;l&eacute;ments",
                    info: "Affichage de l'&eacute;lement _START_ &agrave; _END_ sur _TOTAL_ &eacute;l&eacute;ments",
                    paginate : {
                        first : '<i class="fa fa-fast-backward" aria-hidden="true"></i>',
                        previous : '<i class="fa fa-chevron-circle-left" aria-hidden="true"></i>',
                        next : '<i class="fa fa-chevron-circle-right" aria-hidden="true"></i>',
                        last: '<i class="fa fa-fast-forward" aria-hidden="true"></i>',
                    }
                },
                ajax: '{!! route('datatables.blogData') !!}',
                columns: [
                    {data: 'id', name: 'id'},
                    {data: 'title', name: 'title'},
                    {data: 'action', name: 'action', orderable: false, searchable: false}
                ]
            });
        });

    </script>
    @endpush
@endsection